AWSTemplateFormatVersion: 2010-09-09

Description: |
  AWSBOT AWS CloudFormation template: Root Stack CloudFormation template for A Scalable MultiSite Wordpress website.
  This includes an ElasticBeanstalk application, RDS database, ElastiCache Redis for session management and ElasticSearch
  service.

Parameters:
  Environment:
    Type: String
    Description: The system environment, e.g. dev, test, prod
    AllowedValues:
      - dev
      - test
      - prod

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "General Settings"
        Parameters:
          - Environment

Resources:
   Elasticsearch:
     Type: "AWS::CloudFormation::Stack"
     Properties:
       Parameters:
         Environment: !Ref Environment
       Tags:
         - Key: Environment
           Value: !Ref Environment
       TemplateURL:
       TimeoutInMinutes: 60


   Elasticache:
     Type: "AWS::CloudFormation::Stack"
     Properties:
       Parameters:
       Tags:
         - Key: Environment
           Value: !Ref Environment
       TemplateURL: ''
       TimeoutInMinutes: 60

   Rds:
     Type: "AWS::CloudFormation::Stack"
     Properties:
       Parameters:
         Environment: !Ref Environment
       Tags:
         - Key: Environment
           Value: !Ref Environment
       TemplateURL: ''
       TimeoutInMinutes: 180

  Beanstalk:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        Environment: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment
      TemplateURL: ''
      TimeoutInMinutes: 60
